import os


WOO_HOST = os.environ.get('WOO_HOST')

#Enter here languages for requests
LANGUAGES = os.environ.get('LANGUAGES', 'it').split(',')

#Enter here your WooCommerce key credentials
WOO_CONSUMER_KEY = os.environ.get('WOO_CONSUMER_KEY')
WOO_CONSUMER_SECRET = os.environ.get('WOO_CONSUMER_SECRET')

#Enter here your XML feed fields
XML_FEED_FILENAME = os.environ.get('XML_FEED_FILENAME', 'feedXML')
XML_SITE_NAME = os.environ.get('XML_SITE_NAME')
XML_SITE_HOST = os.environ.get('XML_SITE_HOST')
XML_FEED_DESCRIPTION = os.environ.get('XML_FEED_DESCRIPTION', 'Feed XML autogenerated')
XML_GOOGLE_PRODUCT_CATEGORY = os.environ.get('XML_GOOGLE_PRODUCT_CATEGORY')

REDIS_HOST = os.environ.get('REDIS_HOST', 'redis')
